import { Spot } from "@/types";

export const NIGERIAN_STATES: { id: string; name: string; tag: string }[] = [
  { id: "Lagos", name: "Lagos", tag: "Centre of Excellence" },
  { id: "Abuja (FCT)", name: "Abuja (FCT)", tag: "Federal Capital" },
  { id: "Oyo", name: "Oyo (Ibadan)", tag: "Pacesetter State" },
  { id: "Rivers", name: "Rivers (Port Harcourt)", tag: "Treasure Base" },
  { id: "Enugu", name: "Enugu", tag: "Coal City State" },
  { id: "Cross River", name: "Cross River (Calabar)", tag: "The People's Paradise" },
  { id: "Ogun", name: "Ogun (Abeokuta)", tag: "Gateway State" },
];

export const CATEGORIES = [
  "All",
  "Eatery & Dining",
  "Bars & Lounges",
  "Historical & Memory",
  "Nature & Parks",
  "Arts & Culture",
] as const;

export const MOCK_SPOTS: Spot[] = [
  {
    id: "spot-1",
    name: "Lekki Conservation Centre",
    category: "Nature & Parks",
    priceRating: "₦₦",
    priceRange: "₦2,500 - ₦5,000 / person",
    city: "Lekki",
    state: "Lagos",
    address: "Km 19 Lekki - Epe Expy, Lekki Peninsula II, Lekki",
    description: "Experience Africa's longest canopy walkway (401m), serene coastal nature reserves, monkeys, 100-year-old giant tortoises, and rich mangrove vegetation.",
    imageUrl: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=1000&q=80",
    rating: 4.8,
    reviewsCount: 3840,
    openingHours: "Open Daily • 8:30 AM - 5:00 PM",
    distance: "Lekki Peninsula • 3.2 km away",
    amenities: ["Canopy Walkway", "Picnic Park", "Family Friendly", "Nature Trail", "Chess Court"],
    featured: true,
    tags: ["Canopy Walk", "Nature Reserve", "Wildlife", "Eco Tourism"],
  },
  {
    id: "spot-2",
    name: "Nike Art Gallery",
    category: "Arts & Culture",
    priceRating: "Free",
    priceRange: "Free Admission",
    city: "Lekki Phase 1",
    state: "Lagos",
    address: "2 Elegushi Beach Rd, Lekki Phase I, Lagos",
    description: "West Africa's largest private art gallery spanning 5 soaring floors, displaying over 8,000 diverse Nigerian contemporary artworks, curated by Chief Nike Davies-Okundaye.",
    imageUrl: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1000&q=80",
    rating: 4.9,
    reviewsCount: 4920,
    openingHours: "Mon-Sat • 10:00 AM - 6:00 PM",
    distance: "Lekki Phase 1 • 1.8 km away",
    amenities: ["Free Entry", "Guided Tours", "Art Workshop", "Gift Shop", "Air Conditioned"],
    featured: true,
    tags: ["Art", "African Culture", "Sculpture", "Textiles"],
  },
  {
    id: "spot-3",
    name: "Freedom Park Lagos",
    category: "Historical & Memory",
    priceRating: "₦",
    priceRange: "₦500 - ₦2,000 entry",
    city: "Lagos Island",
    state: "Lagos",
    address: "Broad Street, Lagos Island, Lagos",
    description: "Former colonial Broad Street Prison transformed into a vibrant cultural heritage monument, concert amphitheatre, historical museum, and peaceful arts sanctuary.",
    imageUrl: "https://images.unsplash.com/photo-1518998053901-5348d3961a04?auto=format&fit=crop&w=1000&q=80",
    rating: 4.6,
    reviewsCount: 2150,
    openingHours: "Open Daily • 10:00 AM - 10:00 PM",
    distance: "Lagos Island • 6.4 km away",
    amenities: ["Live Stage", "Museum", "Food Stalls", "Night Performances", "Outdoor Seating"],
    tags: ["Colonial Heritage", "Museum", "Live Music", "Broad Street"],
  },
  {
    id: "spot-4",
    name: "Terra Kulture",
    category: "Arts & Culture",
    priceRating: "₦₦",
    priceRange: "₦4,000 - ₦15,000",
    city: "Victoria Island",
    state: "Lagos",
    address: "Plot 1376 Tiamiyu Savage St, Victoria Island, Lagos",
    description: "An iconic cultural powerhouse featuring Broadway-quality stage theater, indigenous restaurant serving spicy jollof and pounded yam, bookstore, and rotating art exhibitions.",
    imageUrl: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=1000&q=80",
    rating: 4.7,
    reviewsCount: 3100,
    openingHours: "Tue-Sun • 9:30 AM - 10:00 PM",
    distance: "Victoria Island • 4.1 km away",
    amenities: ["Stage Theater", "Authentic Dining", "Bookstore", "Free WiFi", "Valet Parking"],
    tags: ["Theatre", "Bookstore", "Suya & Dining", "Plays"],
  },
  {
    id: "spot-5",
    name: "Yellow Chilli Restaurant",
    category: "Eatery & Dining",
    priceRating: "₦₦₦",
    priceRange: "₦8,000 - ₦25,000 / person",
    city: "Victoria Island",
    state: "Lagos",
    address: "27 Oju Olobun Cl, Victoria Island, Lagos",
    description: "Contemporary pan-African bistro celebrated for signature seafood okra, jollof fiesta, and savory local gourmet delicacies in an upscale, mood-lit dining setting.",
    imageUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1000&q=80",
    rating: 4.6,
    reviewsCount: 1890,
    openingHours: "Daily • 12:00 PM - 11:30 PM",
    distance: "Victoria Island • 4.8 km away",
    amenities: ["Fine Dining", "Cocktail Bar", "Private Rooms", "Takeout", "Wine Cellar"],
    tags: ["Seafood Okra", "Fine Dining", "Lagos Vibe", "Afro-Fusion"],
  },
  {
    id: "spot-6",
    name: "Moist Beach Club",
    category: "Bars & Lounges",
    priceRating: "₦₦₦",
    priceRange: "₦10,000 - ₦35,000",
    city: "Oniru, Victoria Island",
    state: "Lagos",
    address: "Iru Beach, Ligali Ayorinde St, Victoria Island, Lagos",
    description: "Private oceanfront beach lounge with panoramic Atlantic sunset views, craft signature cocktails, live DJ sunset sets, private cabanas, and fresh grilled seafood.",
    imageUrl: "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1000&q=80",
    rating: 4.6,
    reviewsCount: 2750,
    openingHours: "Open Daily • 1:00 PM - Late Night",
    distance: "Oniru Waterfront • 5.0 km away",
    amenities: ["Beachfront", "Pool & Jacuzzi", "Live DJ", "Ocean Cabanas", "Shisha Lounge"],
    tags: ["Beachfront", "Cocktails", "Nightlife", "Sunset"],
  },
  {
    id: "spot-7",
    name: "Zuma Rock",
    category: "Nature & Parks",
    priceRating: "Free",
    priceRange: "Scenic Viewing • Free",
    city: "Madalla",
    state: "Abuja (FCT)",
    address: "Zuma Rock Outskirts, Abuja-Kaduna Highway",
    description: "The majestic 'Gateway to Abuja' monolithic inselberg rising 725 meters with a natural facial contour, steeped in folklore, wonder, and epic panoramic photography.",
    imageUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80",
    rating: 4.8,
    reviewsCount: 5120,
    openingHours: "Open 24/7 • Daylight Best",
    distance: "Abuja Border • 35 mins from City Centre",
    amenities: ["Scenic Lookout", "Photo Spot", "Free Access", "Hiking Access"],
    featured: true,
    tags: ["Monolith", "Landmark", "Iconic", "Hiking"],
  },
  {
    id: "spot-8",
    name: "Jabi Lake & Waterfront Lounge",
    category: "Bars & Lounges",
    priceRating: "₦₦",
    priceRange: "₦3,000 - ₦15,000",
    city: "Jabi",
    state: "Abuja (FCT)",
    address: "Bala Sokoto Way, Jabi, Abuja",
    description: "Picturesque waterfront boardwalk offering speed boat rides, evening acoustic live music, shisha, chilled drinks, and breath-taking sunset views over Jabi Lake.",
    imageUrl: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1000&q=80",
    rating: 4.6,
    reviewsCount: 4200,
    openingHours: "Open Daily • 10:00 AM - 11:00 PM",
    distance: "Jabi District • 5.2 km away",
    amenities: ["Boat Rides", "Waterfront Seating", "Live Music", "Shopping Mall Access", "Cocktails"],
    tags: ["Lake View", "Sunset", "Boat Ride", "Acoustic"],
  },
  {
    id: "spot-9",
    name: "Millennium Park",
    category: "Nature & Parks",
    priceRating: "Free",
    priceRange: "Free Public Access",
    city: "Maitama",
    state: "Abuja (FCT)",
    address: "5 Usuma St, Three Arms Zone, Abuja",
    description: "The largest public park in Abuja commissioned by Queen Elizabeth II, featuring manicured Italian-style gardens, river crossings, tranquil fountains, and lush green lawns.",
    imageUrl: "https://images.unsplash.com/photo-1519331379826-f10be5486c6f?auto=format&fit=crop&w=1000&q=80",
    rating: 4.7,
    reviewsCount: 3600,
    openingHours: "Daily • 6:00 AM - 8:00 PM",
    distance: "Maitama • 2.1 km from Central Area",
    amenities: ["Italian Gardens", "River Walk", "Family Picnics", "Jogging Trail", "Safe & Gated"],
    tags: ["Italian Garden", "Family Picnic", "Walkway", "Peaceful"],
  },
  {
    id: "spot-10",
    name: "The View Restaurant & Lounge",
    category: "Eatery & Dining",
    priceRating: "₦₦₦",
    priceRange: "₦12,000 - ₦30,000",
    city: "Guzape",
    state: "Abuja (FCT)",
    address: "Plot 373 Diplomatic Drive, Guzape Hills, Abuja",
    description: "Perched atop the scenic Guzape hills providing a sweeping 360-degree night skyline of Abuja with gourmet fusion dining, craft cocktails, and romantic ambiance.",
    imageUrl: "https://images.unsplash.com/photo-1543007630-9710e4a00a20?auto=format&fit=crop&w=1000&q=80",
    rating: 4.9,
    reviewsCount: 1650,
    openingHours: "Daily • 2:00 PM - 1:00 AM",
    distance: "Guzape Hills • 10 mins from Central Area",
    amenities: ["Rooftop Skyline", "Romantic Ambience", "Mixology", "Outdoor Terrace", "Fine Steaks"],
    tags: ["Hilltop View", "Skyline", "Gourmet", "Rooftop"],
  },
  {
    id: "spot-11",
    name: "Cocoa House",
    category: "Historical & Memory",
    priceRating: "₦",
    priceRange: "₦1,000 - ₦3,000 entry",
    city: "Dugbe, Ibadan",
    state: "Oyo",
    address: "Bank Road, Dugbe Commercial Area, Ibadan",
    description: "The first skyscraper built in tropical Africa (1965), rising 26 stories funded entirely from the exports of cocoa by Chief Obafemi Awolowo's western administration.",
    imageUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1000&q=80",
    rating: 4.5,
    reviewsCount: 2800,
    openingHours: "Mon-Sat • 9:00 AM - 6:00 PM",
    distance: "Dugbe Central • Ibadan",
    amenities: ["Museum Floor", "Panoramic Rooftop", "Historical Archive", "Elevators"],
    featured: true,
    tags: ["Skyscraper History", "First in Africa", "Heritage", "Cocoa"],
  },
  {
    id: "spot-12",
    name: "Agodi Gardens",
    category: "Nature & Parks",
    priceRating: "₦",
    priceRange: "₦1,000 / person",
    city: "Mokola, Ibadan",
    state: "Oyo",
    address: "Parliament Road, Mokola Hill, Ibadan",
    description: "150-acre tropical park oasis equipped with botanical walk paths, swimming pools, animal sanctuary, forestry, and shaded relaxation cabanas.",
    imageUrl: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1000&q=80",
    rating: 4.4,
    reviewsCount: 3400,
    openingHours: "Open Daily • 10:00 AM - 7:00 PM",
    distance: "Mokola Hill • 3.5 km away",
    amenities: ["Swimming Pools", "Mini Zoo", "Forest Canopy", "Playground", "Boat Rides"],
    tags: ["Botanical Garden", "Pools", "Forestry", "Sanctuary"],
  },
  {
    id: "spot-13",
    name: "Amala Skye (Ose Olorun Canteen)",
    category: "Eatery & Dining",
    priceRating: "₦",
    priceRange: "₦1,500 - ₦4,000 / meal",
    city: "Bodija, Ibadan",
    state: "Oyo",
    address: "Near Omorinre Junction, Bodija, Ibadan",
    description: "Nigeria's most legendary spot for steaming hot fluffy Amala, rich gbegiri, ewedu, and assorted goat meat, cow leg, and fresh savory orishirishi.",
    imageUrl: "https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?auto=format&fit=crop&w=1000&q=80",
    rating: 4.9,
    reviewsCount: 6800,
    openingHours: "Daily • 8:00 AM - 6:00 PM",
    distance: "Bodija • Ibadan",
    amenities: ["Authentic Naija Dishes", "Fast Service", "Takeaway Packs", "Outdoor Seating"],
    tags: ["Legendary Amala", "Gbegiri & Ewedu", "Authentic Naija", "Iconic"],
  },
  {
    id: "spot-14",
    name: "Olumo Rock",
    category: "Historical & Memory",
    priceRating: "₦₦",
    priceRange: "₦2,000 - ₦4,000 entry",
    city: "Abeokuta",
    state: "Ogun",
    address: "Ikija, Abeokuta, Ogun State",
    description: "Ancient natural fortress and sacred rock sanctuary that sheltered the Egba people during the 19th-century tribal wars, featuring glass elevators, natural caves, and panoramic vistas.",
    imageUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1000&q=80",
    rating: 4.7,
    reviewsCount: 4500,
    openingHours: "Daily • 8:30 AM - 6:00 PM",
    distance: "Ikija • Abeokuta",
    amenities: ["Glass Elevator", "Cave Shrines", "Tour Guides", "Summit Vistas", "Art Market"],
    featured: true,
    tags: ["Sacred Rock", "Egba Heritage", "Mountain View", "Cave"],
  },
  {
    id: "spot-15",
    name: "Port Harcourt Pleasure Park",
    category: "Nature & Parks",
    priceRating: "₦",
    priceRange: "₦1,000 - ₦5,000",
    city: "Port Harcourt",
    state: "Rivers",
    address: "Aba Road, Rumuola, Port Harcourt",
    description: "Premier entertainment park destination in the Niger Delta boasting pedal boats on artificial lakes, mini golf, fitness climbing trails, shaded lounge spots, and children's amusement.",
    imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1000&q=80",
    rating: 4.6,
    reviewsCount: 3100,
    openingHours: "Daily • 9:00 AM - 9:00 PM",
    distance: "Aba Road • Port Harcourt",
    amenities: ["Pedal Boats", "Mini Golf", "Climbing Tower", "Jogging Path", "Food Court"],
    tags: ["Boating", "Green Park", "Garden City", "Family Fun"],
  },
];
